export const data = [
  {
    BoundaryType: "SentenceBoundary",
    Text: "Microsoft introduces a multimodal large language model called Kosmos-1.Achieves great performance on language understanding, OCR-free NLP, perception-language tasks, visual QA, and more.Take a look at some of the examples of generations from the Kosmos-1 model that can perceive general modalities.",
    AudioOffset: "50ms",
    Duration: "19300ms",
    TextOffset: 284,
    WordLength: 0,
    Words: [
      {
        BoundaryType: "WordBoundary",
        Text: "Microsoft",
        AudioOffset: "50ms",
        Duration: "637.5ms",
        TextOffset: 284,
        WordLength: 9,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "introduces",
        AudioOffset: "700ms",
        Duration: "737.5ms",
        TextOffset: 294,
        WordLength: 10,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "a",
        AudioOffset: "1487.5ms",
        Duration: "37.5ms",
        TextOffset: 305,
        WordLength: 1,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "multimodal",
        AudioOffset: "1537.5ms",
        Duration: "650ms",
        TextOffset: 307,
        WordLength: 10,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "large",
        AudioOffset: "2200ms",
        Duration: "325ms",
        TextOffset: 318,
        WordLength: 5,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "language",
        AudioOffset: "2537.5ms",
        Duration: "437.5ms",
        TextOffset: 324,
        WordLength: 8,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "model",
        AudioOffset: "2987.5ms",
        Duration: "350ms",
        TextOffset: 333,
        WordLength: 5,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "called",
        AudioOffset: "3350ms",
        Duration: "262.5ms",
        TextOffset: 339,
        WordLength: 6,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "Kosmos-1",
        AudioOffset: "3625ms",
        Duration: "962.5ms",
        TextOffset: 346,
        WordLength: 8,
      },
      {
        BoundaryType: "WordBoundary",
        Text: ".",
        AudioOffset: "4600ms",
        Duration: "212.5ms",
        TextOffset: 354,
        WordLength: 1,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "Achieves",
        AudioOffset: "4825ms",
        Duration: "375ms",
        TextOffset: 355,
        WordLength: 8,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "great",
        AudioOffset: "5212.5ms",
        Duration: "275ms",
        TextOffset: 364,
        WordLength: 5,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "performance",
        AudioOffset: "5500ms",
        Duration: "587.5ms",
        TextOffset: 370,
        WordLength: 11,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "on",
        AudioOffset: "6100ms",
        Duration: "150ms",
        TextOffset: 382,
        WordLength: 2,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "language",
        AudioOffset: "6262.5ms",
        Duration: "400ms",
        TextOffset: 385,
        WordLength: 8,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "understanding",
        AudioOffset: "6675ms",
        Duration: "787.5ms",
        TextOffset: 394,
        WordLength: 13,
      },
      {
        BoundaryType: "PunctuationBoundary",
        Text: ",",
        AudioOffset: "7562.5ms",
        Duration: "62.5ms",
        TextOffset: 407,
        WordLength: 1,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "OCR-free",
        AudioOffset: "7637.5ms",
        Duration: "675ms",
        TextOffset: 409,
        WordLength: 8,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "NLP",
        AudioOffset: "8325ms",
        Duration: "662.5ms",
        TextOffset: 418,
        WordLength: 3,
      },
      {
        BoundaryType: "PunctuationBoundary",
        Text: ",",
        AudioOffset: "9087.5ms",
        Duration: "62.5ms",
        TextOffset: 421,
        WordLength: 1,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "perception-language",
        AudioOffset: "9150ms",
        Duration: "975ms",
        TextOffset: 423,
        WordLength: 19,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "tasks",
        AudioOffset: "10137.5ms",
        Duration: "600ms",
        TextOffset: 443,
        WordLength: 5,
      },
      {
        BoundaryType: "PunctuationBoundary",
        Text: ",",
        AudioOffset: "10837.5ms",
        Duration: "137.5ms",
        TextOffset: 448,
        WordLength: 1,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "visual",
        AudioOffset: "10975ms",
        Duration: "375ms",
        TextOffset: 450,
        WordLength: 6,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "QA",
        AudioOffset: "11362.5ms",
        Duration: "525ms",
        TextOffset: 457,
        WordLength: 2,
      },
      {
        BoundaryType: "PunctuationBoundary",
        Text: ",",
        AudioOffset: "11987.5ms",
        Duration: "100ms",
        TextOffset: 459,
        WordLength: 1,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "and",
        AudioOffset: "12087.5ms",
        Duration: "150ms",
        TextOffset: 461,
        WordLength: 3,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "more",
        AudioOffset: "12250ms",
        Duration: "350ms",
        TextOffset: 465,
        WordLength: 4,
      },
      {
        BoundaryType: "PunctuationBoundary",
        Text: ".",
        AudioOffset: "12612.5ms",
        Duration: "0ms",
        TextOffset: 469,
        WordLength: 1,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "Take",
        AudioOffset: "12612.5ms",
        Duration: "225ms",
        TextOffset: 470,
        WordLength: 4,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "a",
        AudioOffset: "12850ms",
        Duration: "50ms",
        TextOffset: 475,
        WordLength: 1,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "look",
        AudioOffset: "12912.5ms",
        Duration: "225ms",
        TextOffset: 477,
        WordLength: 4,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "at",
        AudioOffset: "13150ms",
        Duration: "112.5ms",
        TextOffset: 482,
        WordLength: 2,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "some",
        AudioOffset: "13275ms",
        Duration: "175ms",
        TextOffset: 485,
        WordLength: 4,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "of",
        AudioOffset: "13462.5ms",
        Duration: "75ms",
        TextOffset: 490,
        WordLength: 2,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "the",
        AudioOffset: "13550ms",
        Duration: "75ms",
        TextOffset: 493,
        WordLength: 3,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "examples",
        AudioOffset: "13637.5ms",
        Duration: "575ms",
        TextOffset: 497,
        WordLength: 8,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "of",
        AudioOffset: "14225ms",
        Duration: "87.5ms",
        TextOffset: 506,
        WordLength: 2,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "generations",
        AudioOffset: "14325ms",
        Duration: "712.5ms",
        TextOffset: 509,
        WordLength: 11,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "from",
        AudioOffset: "15050ms",
        Duration: "137.5ms",
        TextOffset: 521,
        WordLength: 4,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "the",
        AudioOffset: "15200ms",
        Duration: "100ms",
        TextOffset: 526,
        WordLength: 3,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "Kosmos-1",
        AudioOffset: "15312.5ms",
        Duration: "900ms",
        TextOffset: 530,
        WordLength: 8,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "model",
        AudioOffset: "16225ms",
        Duration: "350ms",
        TextOffset: 539,
        WordLength: 5,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "that",
        AudioOffset: "16587.5ms",
        Duration: "150ms",
        TextOffset: 545,
        WordLength: 4,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "can",
        AudioOffset: "16750ms",
        Duration: "137.5ms",
        TextOffset: 550,
        WordLength: 3,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "perceive",
        AudioOffset: "16900ms",
        Duration: "412.5ms",
        TextOffset: 554,
        WordLength: 8,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "general",
        AudioOffset: "17325ms",
        Duration: "337.5ms",
        TextOffset: 563,
        WordLength: 7,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "modalities",
        AudioOffset: "17675ms",
        Duration: "862.5ms",
        TextOffset: 571,
        WordLength: 10,
      },
      {
        BoundaryType: "PunctuationBoundary",
        Text: ".",
        AudioOffset: "18550ms",
        Duration: "100ms",
        TextOffset: 581,
        WordLength: 1,
      },
    ],
  },
  {
    BoundaryType: "SentenceBoundary",
    Text: "Would love to see how something like this might do with more data-specific visuals like charts, etc.More examples demonstrating visual dialogue capabilities.Okay, I have to admit this one caught my attention.",
    AudioOffset: "19350ms",
    Duration: "12725ms",
    TextOffset: 583,
    WordLength: 0,
    Words: [
      {
        BoundaryType: "WordBoundary",
        Text: "Would",
        AudioOffset: "19400ms",
        Duration: "200ms",
        TextOffset: 583,
        WordLength: 5,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "love",
        AudioOffset: "19612.5ms",
        Duration: "187.5ms",
        TextOffset: 589,
        WordLength: 4,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "to",
        AudioOffset: "19812.5ms",
        Duration: "100ms",
        TextOffset: 594,
        WordLength: 2,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "see",
        AudioOffset: "19925ms",
        Duration: "187.5ms",
        TextOffset: 597,
        WordLength: 3,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "how",
        AudioOffset: "20125ms",
        Duration: "175ms",
        TextOffset: 601,
        WordLength: 3,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "something",
        AudioOffset: "20312.5ms",
        Duration: "387.5ms",
        TextOffset: 605,
        WordLength: 9,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "like",
        AudioOffset: "20712.5ms",
        Duration: "187.5ms",
        TextOffset: 615,
        WordLength: 4,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "this",
        AudioOffset: "20912.5ms",
        Duration: "225ms",
        TextOffset: 620,
        WordLength: 4,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "might",
        AudioOffset: "21150ms",
        Duration: "262.5ms",
        TextOffset: 625,
        WordLength: 5,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "do",
        AudioOffset: "21425ms",
        Duration: "337.5ms",
        TextOffset: 631,
        WordLength: 2,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "with",
        AudioOffset: "21825ms",
        Duration: "162.5ms",
        TextOffset: 634,
        WordLength: 4,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "more",
        AudioOffset: "22000ms",
        Duration: "225ms",
        TextOffset: 639,
        WordLength: 4,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "data-specific",
        AudioOffset: "22237.5ms",
        Duration: "800ms",
        TextOffset: 644,
        WordLength: 13,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "visuals",
        AudioOffset: "23050ms",
        Duration: "437.5ms",
        TextOffset: 658,
        WordLength: 7,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "like",
        AudioOffset: "23500ms",
        Duration: "175ms",
        TextOffset: 666,
        WordLength: 4,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "charts",
        AudioOffset: "23687.5ms",
        Duration: "487.5ms",
        TextOffset: 671,
        WordLength: 6,
      },
      {
        BoundaryType: "PunctuationBoundary",
        Text: ",",
        AudioOffset: "24275ms",
        Duration: "112.5ms",
        TextOffset: 677,
        WordLength: 1,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "etc.",
        AudioOffset: "24387.5ms",
        Duration: "525ms",
        TextOffset: 679,
        WordLength: 4,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "More",
        AudioOffset: "25012.5ms",
        Duration: "187.5ms",
        TextOffset: 683,
        WordLength: 4,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "examples",
        AudioOffset: "25212.5ms",
        Duration: "537.5ms",
        TextOffset: 688,
        WordLength: 8,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "demonstrating",
        AudioOffset: "25762.5ms",
        Duration: "700ms",
        TextOffset: 697,
        WordLength: 13,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "visual",
        AudioOffset: "26525ms",
        Duration: "362.5ms",
        TextOffset: 711,
        WordLength: 6,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "dialogue",
        AudioOffset: "26900ms",
        Duration: "475ms",
        TextOffset: 718,
        WordLength: 8,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "capabilities",
        AudioOffset: "27387.5ms",
        Duration: "837.5ms",
        TextOffset: 727,
        WordLength: 12,
      },
      {
        BoundaryType: "PunctuationBoundary",
        Text: ".",
        AudioOffset: "28237.5ms",
        Duration: "37.5ms",
        TextOffset: 739,
        WordLength: 1,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "Okay",
        AudioOffset: "28275ms",
        Duration: "450ms",
        TextOffset: 740,
        WordLength: 4,
      },
      {
        BoundaryType: "PunctuationBoundary",
        Text: ",",
        AudioOffset: "28825ms",
        Duration: "137.5ms",
        TextOffset: 744,
        WordLength: 1,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "I",
        AudioOffset: "28962.5ms",
        Duration: "100ms",
        TextOffset: 746,
        WordLength: 1,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "have",
        AudioOffset: "29075ms",
        Duration: "162.5ms",
        TextOffset: 748,
        WordLength: 4,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "to",
        AudioOffset: "29250ms",
        Duration: "112.5ms",
        TextOffset: 753,
        WordLength: 2,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "admit",
        AudioOffset: "29375ms",
        Duration: "312.5ms",
        TextOffset: 756,
        WordLength: 5,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "this",
        AudioOffset: "29700ms",
        Duration: "200ms",
        TextOffset: 762,
        WordLength: 4,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "one",
        AudioOffset: "29912.5ms",
        Duration: "212.5ms",
        TextOffset: 767,
        WordLength: 3,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "caught",
        AudioOffset: "30137.5ms",
        Duration: "250ms",
        TextOffset: 771,
        WordLength: 6,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "my",
        AudioOffset: "30400ms",
        Duration: "162.5ms",
        TextOffset: 778,
        WordLength: 2,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "attention",
        AudioOffset: "30575ms",
        Duration: "687.5ms",
        TextOffset: 781,
        WordLength: 9,
      },
      {
        BoundaryType: "PunctuationBoundary",
        Text: ".",
        AudioOffset: "31275ms",
        Duration: "100ms",
        TextOffset: 790,
        WordLength: 1,
      },
    ],
  },
  {
    BoundaryType: "SentenceBoundary",
    Text: "Results on the Raven IQ test.",
    AudioOffset: "32075ms",
    Duration: "2787.5ms",
    TextOffset: 792,
    WordLength: 0,
    Words: [
      {
        BoundaryType: "WordBoundary",
        Text: "Results",
        AudioOffset: "32125ms",
        Duration: "425ms",
        TextOffset: 792,
        WordLength: 7,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "on",
        AudioOffset: "32562.5ms",
        Duration: "112.5ms",
        TextOffset: 800,
        WordLength: 2,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "the",
        AudioOffset: "32687.5ms",
        Duration: "87.5ms",
        TextOffset: 803,
        WordLength: 3,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "Raven",
        AudioOffset: "32787.5ms",
        Duration: "312.5ms",
        TextOffset: 807,
        WordLength: 5,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "IQ",
        AudioOffset: "33112.5ms",
        Duration: "312.5ms",
        TextOffset: 813,
        WordLength: 2,
      },
      {
        BoundaryType: "WordBoundary",
        Text: "test",
        AudioOffset: "33437.5ms",
        Duration: "612.5ms",
        TextOffset: 816,
        WordLength: 4,
      },
      {
        BoundaryType: "PunctuationBoundary",
        Text: ".",
        AudioOffset: "34062.5ms",
        Duration: "100ms",
        TextOffset: 820,
        WordLength: 1,
      },
    ],
  },
];
